sudo: true
dist: trusty


before_install:
  - for f in content/post/*.html; do \
      echo $f; \
      curl -s -H "Content-Type: text/html; charset=utf-8" --data-binary @$f https://validator.w3.org/nu/?out=text; \
      echo ""; \
      done

      
install:
  - sudo apt-get --yes install snapd
  - sudo snap install hugo
  - rm -rf public || exit 0
  
script:
  - /snap/bin/hugo

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
