sudo: true
dist: trusty

install:
  - sudo apt-get --yes install snapd
  - sudo snap install hugo
  - rm -rf public || exit 0

script:
  - /snap/bin/hugo

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
