baseurl = "/blog-sandbox/"
languageCode = "en-us"
title = "R Consortium Wordpress Integration Sandbox"
theme = "rconsortium-demo-theme"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Projects"
    url = "/projects/"
[[menu.main]]
    name = "Members"
    url = "/members/"
[[menu.main]]
    name = "News"
    url = "/news/"
[[menu.main]]
    name = "Contact"
    url = "/contact/"

    
[params]
    description = "Demo of R Consortium site layout."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "RConsortium_Horizontal_Pantone.png"
    width = 200
    height = 60
    alt = "Logo"
    
    [params.banner]
    url = "logo_lf_projects_horizontal_2018.png"
    width = 300
    height = 15
    alt = "Linux Foundation"

