---
title: Gordon and Betty Moore Foundation Joins R Consortium to Encourage Development,
  Maintenance and Distribution of R Software
author: Penny
date: '2017-01-11'
categories:
  - Announcement
  - News
slug: gordon-and-betty-moore-foundation-joins-r-consortium-to-encourage-development-maintenance-and-distribution-of-r-software
---

_Grant is a part of the Moore Foundation's Data-Driven Discovery Initiative to support data scientists _

**SAN FRANCISCO – [Jan 11, 2017, 10:00 ET] –** The [R Consortium](https://www.r-consortium.org/), an open source foundation supporting the R user community and a Linux Foundation project, today welcomed the Gordon and Betty Moore Foundation to the Consortium as a supporting Platinum member. The Moore Foundation grant will enable the R Consortium to expand its support for the community developing, maintaining, distributing and using the R programming language.

Thousands of statisticians, analysts and scientists worldwide rely on the R language to allow them to analyze, model and visualize large, complex datasets and to create statistical software. In addition, R provides interfaces to other computing platforms, providing users with access to the best computations for understanding data. Interest in the language is growing across industries that rely on statistical computing, such as healthcare and finance, as well as newer disciplines like machine learning.

The Moore Foundation was established to create positive outcomes for future generations. In pursuit of that vision, the Foundation fosters path-breaking scientific discovery, environmental conservation, patient care improvements and preservation of the character of the San Francisco Bay Area. As part of its work to support scientific discovery, the Moore Foundation has a $60 million initiative in Data-Driven Discovery that supports new ways to effectively harness scientific datasets that are so large and complex that they require use of fundamentally different techniques and better tools. Participation in the R Consortium is a part of the Moore Foundation's efforts to encourage progress in data science practice.

"The Moore Foundation has joined the R Consortium because we want to further the organization's mission of supporting the R community," said Chris Mentzel, program director of the Moore Foundation's Data-Driven Discovery Initiative. "The R language and packages are well established and widely used, but is still incredibly dynamic due to strong community involvement and evolving needs of scientists, statisticians and many others. We believe our support will help the community continue to create technology that is freely available to all who want to leverage modern scale scientific data for new discoveries."

Mr. Mentzel will participate in meetings of the Board of Directors and the Infrastructure Steering Committee (ISC), which provides support and technical guidance to the R community.

"We're delighted to welcome the Moore Foundation as a member of the R Consortium," said Louis Bajuk-Yorgan, chair of the R Consortium Board of Directors and senior director of product management, streaming and advanced analytics at TIBCO Software. "The organization's participation will permit us to intensify our support through the Infrastructure Steering Committee for development of new projects for the benefit of the full R community."

**R Consortium ISC Accepting Proposals**

The infrastructure Steering Committee is now accepting proposals for the first round of funding in 2017. The ISC is broadly interested in projects that will make a difference to the R community.

Infrastructure includes:

  * Ambitious technical projects such as [R-hub](https://www.r-consortium.org/blog/2016/06/06/first-public-version-of-the-r-hub-builder), which require dedicated time to supply infrastructure that is currently missing in the R ecosystem.

  * Community projects like R-ladies and [SatRdays](https://www.r-consortium.org/blog/2016/09/07/the-start-of-satrdays), which help catalyze and support the growth of the R community around the world.

  * Smaller projects to develop packages similar to DBI and sf, which provide key infrastructure used by thousands of R programmers.

The deadline for submitting a proposal is midnight PST on Friday February 10, 2017. For information on the mechanics of submitting a proposal and some guidance on how to write a good proposal, see the [Call for Proposals](https://www.r-consortium.org/projects/call-for-proposals) page.

**About the Gordon and Betty Moore Foundation**

The Gordon and Betty Moore Foundation fosters path-breaking scientific discovery, environmental conservation, patient care improvements and preservation of the special character of the Bay Area. Visit [moore.org](http://moore.org/) and follow @MooreFound.

**About The R Consortium**

The R Consortium is a 501(c)6 nonprofit organization and Linux Foundation project dedicated to the support and growth of the R user community. The R Consortium provides support to the R Foundation and to the greater R Community for projects that assist R package developers, provide documentation and training, facilitate the growth of the R Community and promote the use of the R language. For more information about R Consortium, please visit: <http://www.r-consortium.org>.

# # #

**Media Contact:**

Dan Brown
The Linux Foundation
dbrown@linuxfoundation.org
