---
title: 2018 R Consortium Silver member representatives for Board and ISC
author: John Mertic
date: '2017-12-22'
categories:
  - Announcement
  - Blog
  - News
  - R Consortium Project
slug: 2018-r-consortium-silver-member-representatives-board-isc
---

Per the R Consortium [ByLaws](https://www.r-consortium.org/about/bylaws) and [ISC Charter](https://www.r-consortium.org/about/isc-charter), the Silver Member class is entitled to elect individuals representative of the Silver Member class for a term starting January 1, 2018 through December 31, 2018 as follows:

  * 1 representative to the ISC

  * 1 Silver Member Board Director per every 7 Silver Members, subject to provisions 4.2 and 4.3(d) of the R Consortium ByLaws. This means the Silver Member class can elect up to 2 Board Directors representing the class.

These elections ran during the month of November 2017, with 3 nominees for Silver Member Board Director and 3 nominees for the Silver Member ISC representative.

I am pleased to announce those elected by the Silver member class to serve on the Board of Directors and ISC effective 1/1/2018 through 12/31/2018.

Silver Member ISC representative

  * [Dirk Eddelbuettel](http://dirk.eddelbuettel.com/) - Ketchum Trading

Silver Member Board Directors

  * [Mark Hornick](https://www.linkedin.com/in/markhornick) - Oracle

  * [Chester Ismay](https://www.linkedin.com/in/chesterismay/) - DataCamp

Please join me in congratulating each of the elected representatives.

We would also like the share a big thank you to the outgoing Silver Member Board Director [Richard Pugh](https://www.linkedin.com/in/richard-pugh-08b27a/) of Mango Solutions. His guidance and leadership within the R Consortium have made a huge impact on its current success.
